<?php
namespace backend\controllers;

use common\components\TestBehaivorsMethod;
use common\components\TestBehaviors;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class IndexController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaivors = parent::behaviors();
        $behaivors['TestBehaivors'] = ['class' => TestBehaivorsMethod::className()];
        return $behaivors;
    }

    public function beforeAction($action)
    {
        $resut = parent::beforeAction($action); // TODO: Change the autogenerated stub
        if($resut){
            $this->testBehaiversMethod();
            echo "测试";
            return true;
        }

    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //默认调用一个事件 绑定行为方法
        $this->trigger(TestBehaivorsMethod::AUTO_INIT);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //$this->layout = false;

        $this->testBehaiversMethod();
        return $this->render('index');
    }

    
}
