<?php
/**
 * Created by PhpStorm.
 * User: limr
 * Date: 2017/10/27
 * Time: 0:35
 */

namespace common\components;


use yii\base\Behavior;
use yii\base\Object;

class TestBehaivorsMethod extends Behavior
{
     const AUTO_INIT = "autInit";
     public function events()
     {
          $events =  parent::events(); // TODO: Change the autogenerated stub
          $events[self::AUTO_INIT] = 'autoInit';
          return $events;
     }

     //测试默认实现方法    可以在beforeAction调用  也可注册成事件处理器
     public function testBehaiversMethod(){
          echo "<br>====我是行为内测试方法，我被调用了！=====<br>";
     }

     public function autoInit(){
          echo "<br>我是行为类注册的事件函数:autoInit()<br>";
     }

}